:toc:
:icons:
:linkattrs:

= Migration tips

## Available options
### container-transform
[container-transform](https://github.com/micahhausler/container-transform) is a command-line utility that can be used to convert between different container formats.  It currently supports converting between the following formats: 

* Kubernetes Pod specs
* ECS task definitions
* Docker-compose configuration files
* Marathon Application Definitions or Groups of Applications
* Chronos Task Definitions

You can also send the output to a systemd unit file. 

If you're coming from a non-kubernetes environments, you can use this utility to migrate your container definitions to Kubernetes.   

### Heptio Ark
[Heptio Ark](https://heptio.github.io/ark/v0.8.1/) is a tool that is used to backup and restore your Kubernetes cluster.  

Although Ark doesn't migrate cloud volumes between cloud providers, you may be able to use it to migrate from a self managed k8s cluster running on AWS to EKS with minimal rework.

### [Future] eksctl
The [eksctl](https://eksctl.io/) is a command-line utility written by Weave that can provision a new EKS cluster in 1 step.  While it doesn't support migrations today, there is an open [feature request](https://github.com/weaveworks/eksctl/issues/50) to add this to the CLI.
