:toc:
:icons:
:linkattrs:

= Security tips

== General Kubernetes tips

- Ensure Role-Based Access Control (RBAC) is enabled on your Cluster

    $ kops edit cluster ${NAME}
    ...
    spec:
     authorization:
       rbac: {}
    ...

- Never write Secrets to disk
- Maintain good hygiene with Docker images
** Frequently scan for security vulnerabilities
** Adhere to organization policies while building images and only use authorized images

- Block access to EC2 Instance Metadata

    # let's say I have gained control over your web server running in a pod
    # I can easily find IAM role attached to your EC2 Instance and get the API keys
    $ kubectl exec my-nginx-77f21FDac8-2rasu curl http://169.254.169.254/latest/meta-data/iam/security-credentials/
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100    53  100    53    0     0  44915      0 --:--:-- --:--:-- --:--:-- 53000
    ekscluster-worker-nodes-NodeInstanceRole-73ZAKXJ2G656/
    $ kubectl exec my-nginx-77f21FDac8-2rasu curl http://169.254.169.254/latest/meta-data/iam/security-credentials/ekscluster-worker-nodes-NodeInstanceRole-73ZAKXJ2G656/
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100   882  100   882    0     0   796k      0 --:--:-- --:--:-- --:--:--  861k
    {
      "Code" : "Success",
      "LastUpdated" : "2018-05-11T14:31:58Z",
      "Type" : "AWS-HMAC",
      "AccessKeyId" : "ASIAIXXXXAV36CNSKKYA",
      "SecretAccessKey" : "4NZnAAAAAAAABBBBBBANJ8s6YqWtXOI5PS5XvB/",
      "Token" : "FQoDYXdzAWSKzClQxMx5sg...",
      "Expiration" : "2018-05-11T21:04:10Z"

- Leverage Kubernetes namespaces for isolating environments

== Storing secrets options:

- Community: Vault(1)
- Managed Service: Parameter Store

     (1) Commercial offering

=== Vault
Vault secures, stores, and tightly controls access to tokens, passwords, certificates, API keys, and other secrets in modern computing

- Platform independent
- Secret storage, Key rotation, Audit logs
- High Availability
- Dynamic secrets
- User and server authentication options
- Fine-grained access control
- Good language and tooling support
- Under active development

What are its use cases? Secrets Management, Encryption as a Service, Identity and Access Management

How to get started? https://www.vaultproject.io/intro/getting-started/install.html

How do I use?

    # store secrets
    $ vault write secret/creds GREETING=Hello NAME=World
    Success! Data written to: secret/creds

    # read secrets
    $ vault read secret/creds
    Key               Value
    ---               ----
    refresh_interval  768h0m0s
    GREETING          Hello
    NAME              World
    $ vault read -field=GREETING secret/creds
    Hello

Vault Tips?

- Never provide "root" credentials to your clients
- Enable access based on an IAM role
- Generate on demand secrets upon request
- Leverage Audit logs in case your system is compromised

=== Parameter Store

AWS Parameter Store provides secure, hierarchical storage for configuration data management and secrets management.

- Part of AWS Systems Manager toolset
- Integrated with AWS services (CloudFormation, ECS... etc)
- Supports Key Management Service (KMS) encyption
- Audit trail is logged in CloudTrail
- No additional charge

What are its use cases? Managing Secrets and Configuration data

How to get started? https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html#sysman-paramstore-gs

How do I use?

    # store secrets
    $ aws ssm put-parameter \
      --name GREETING --value Hello \
      --type SecureString \
      --key-id 59ddde10-7849-475c-b32c-acc4923f4ebe

    # read secrets
    $ aws ssm get-parameter --name GREETING
    {
        "Parameter": {
            "Version": 1,
            "Type": "SecureString",
            "Name": "GREETING",
            "Value": "AQICAHiPZuTFyN+UYY0Zaz6j112VjYXbhJBfydCgIm1+FUsEGQEb8IRcHBLHa2o2q1DD/kMzAAAAYzBhBgkqhkiG9w0BBwagVDBSAgEAME0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMD1Udc7QHy60IB5qrAgEQgCBi1znSGkxLPB7KmWdtaPocs4ILERjX3VaJDi8dV2maFg=="
        }
    }

    # read secrets in clear text
    $ aws ssm get-parameter --name GREETING --with-decryption
    {
        "Parameter": {
            "Name": "GREETING",
            "Type": "SecureString",
            "Value": "Hello",
            "Version": 1
        }
    }

AWS Parameter Store Tips?


== IAM Roles options:
Before we go into available options, let's define why is this important. 

- Community: kube2IAM, kiam


== Namespace isolation
